### ISSUE TITLE
Running the tests on unmodified master gives printouts (diffs)

### ISSUE THREAD

**Issue by fredrik-sk** [rscada/libmbus#163] opened 2020-06-05 14:16 UTC
I created a Dockerfile to run the tests, and ran the tests on an unmodified master.
And I got a bunch of printouts (diff).

https://github.com/fredrik-sk/libmbus/runs/742450655?check_suite_focus=true

EDIT: Here is a copy of the printouts.
```
--- test/test-frames/electricity-meter-2.xml	2020-06-05 13:47:48.073790560 +0000
+++ test/test-frames/electricity-meter-2.xml.new	2020-06-05 13:47:51.117813164 +0000
@@ -2,7 +2,7 @@
 <MBusData>
 
     <SlaveInformation>
-        <Id>5000345</Id>
+        <Id>5000205</Id>
         <Manufacturer>@@@</Manufacturer>
         <Version>18</Version>
         <ProductName></ProductName>

mbus_parse: Invalid M-Bus frame length.
Unable to generate XML for test/test-frames/invalid_length.hex
mbus_frame_data_parse: Invalid length for fixed data.
Unable to generate XML for test/test-frames/invalid_length2.hex
--- test/test-frames/landis+gyr_ultraheat_t230.xml	2020-06-05 13:47:48.077790590 +0000
+++ test/test-frames/landis+gyr_ultraheat_t230.xml.new	2020-06-05 13:47:51.225813961 +0000
@@ -72,7 +72,7 @@
         <Function>Instantaneous value</Function>
         <StorageNumber>0</StorageNumber>
         <Unit>Temperature Difference (1e-1  deg C)</Unit>
-        <Value>1500002</Value>
+        <Value>-2</Value>
     </DataRecord>
 
     <DataRecord id="9">

```

**Comment by fredrik-sk** [comment] 2020-06-08 17:48
Update: Some more research showed that this was introduced by commit 2f9fa5ccc8aa032556ab77b7cafcb24670b6bf8d, the code was updated but not the tests.
Reverting that commit makes the test run clean again.

I will look into this some more.

Added a comment:
According to wikipedia ( https://en.wikipedia.org/wiki/Binary-coded_decimal , section Packed BCD), 0xF0 should be interpreted as a positve number.

https://github.com/rscada/libmbus/commit/2f9fa5ccc8aa032556ab77b7cafcb24670b6bf8d#r39755040

**Comment by lategoodbye** [comment] 2020-06-27 13:01
I think, i've found a solution. Unfortunately we have a regression in #151 which must be fixed first.

**Comment by Apollon77** [comment] 2020-06-30 22:39
I also have such a case ... I brought my branch of libmbus which is used to buil "node-mbus" to the current status of the master but my Node-mbs tests fail because also here I have one case where the "SlaveInformation.Id" field changes.

I already have the "improved BCD decoding" commit in too!

**Comment by lategoodbye** [comment] 2020-07-01 06:07
@Apollon77 Your hex contains 3E020005 which is actually slave id 500023E. I'm not sure it's allowed to have hex digits in a slave id and i don't know this comes from a real device. But make libmbus hiding this issue to make your tests succeed doesn't make sense to me.

So please describe your expectations.

**Comment by Apollon77** [comment] 2020-07-01 06:58
@lategoodbye if it is that way I'm fine ... then this change is "simply because decoding was broken before" and so it is fixed now :-) I was just wondering which is right ... When I remember correctly I had that "data string" from a real device. Then I fix the test expectation!

**Comment by lategoodbye** [comment] 2020-07-08 10:07
I consider this as fixed

**Closed by lategoodbye** 2020-07-08 10:07 UTC
